#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3
bspc config border_width         0
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a tilix desktop='^1'
bspc rule -a code desktop='^3'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a code desktop='^5'

# polybar
$HOME/.config/polybar/launch.sh 
# --hack

# picom
picom --experimental-backends -b

# nitrogen
nitrogen --restore

#chown teenarp2003 /sys/class/backlight/amdgpu_bl0/brightness
# sudo chgrp video  /sys/class/backlight/amdgpu_bl0/brightness
