#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6
bspc config border_width         2
bspc config window_gap           6


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a Google-chrome desktop='^2' -l monocle
bspc rule -a firefox desktop='^2'
bspc rule -a Spotify desktop='^4' -l monocle
bspc rule -a GitKraken desktop='^5'
bspc rule -a Code desktop='^3'
bspc rule -a Screenkey manage=off
bspc rule -a env LD_PRELOAD=/usr/lib/spotify-adblock.so spotify %U desktop='^4'

# polybar
$HOME/.config/polybar/launch.sh 
# --hack

# picom
picom --experimental-backends -b

# nitrogen
nitrogen --restore

#chown teenarp2003 /sys/class/backlight/amdgpu_bl0/brightness
# sudo chgrp video  /sys/class/backlight/amdgpu_bl0/brightness
